name: 🚀 Build & Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build-windows:
    name: 🪟 Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run build:renderer
        env: { NODE_ENV: production }
      - name: Build Electron
        env: { GH_TOKEN: '${{ secrets.GH_TOKEN }}' }
        run: npx electron-builder --win --config electron-builder.yml
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist-electron/*.exe
            dist-electron/latest.yml
        env: { GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}' }

  build-linux:
    name: 🐧 Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: sudo apt-get install -y rpm fakeroot
      - run: npm ci
      - run: npm run build:renderer
        env: { NODE_ENV: production }
      - name: Build Electron
        env: { GH_TOKEN: '${{ secrets.GH_TOKEN }}' }
        run: npx electron-builder --linux --config electron-builder.yml
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist-electron/*.AppImage
            dist-electron/*.deb
            dist-electron/latest-linux.yml
        env: { GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}' }

  build-mac:
    name: 🍎 macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run build:renderer
        env: { NODE_ENV: production }
      - name: Build Electron
        env:
          GH_TOKEN: '${{ secrets.GH_TOKEN }}'
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npx electron-builder --mac --config electron-builder.yml
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist-electron/*.dmg
            dist-electron/latest-mac.yml
        env: { GITHUB_TOKEN: '${{ secrets.GH_TOKEN }}' }

